-- Ocean Cleanup Backend
-- PostgreSQL schema for the current JSON-backed API

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'contributor', 'verifier');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
        CREATE TYPE activity_status AS ENUM ('pending', 'rejected', 'approved');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id              TEXT PRIMARY KEY,
    first_name      TEXT NOT NULL,
    last_name       TEXT NOT NULL,
    email           TEXT NOT NULL,
    username        TEXT NOT NULL,
    password_hash   TEXT NOT NULL,
    role            user_role NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_username_unique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS activities (
    id                  TEXT PRIMARY KEY,
    category            TEXT NOT NULL,
    location            TEXT NOT NULL,
    quantity            NUMERIC(12, 2) NOT NULL CHECK (quantity >= 0),
    volunteers          INTEGER NOT NULL DEFAULT 0 CHECK (volunteers >= 0),
    evidence_hash       TEXT,
    contributor_id      TEXT,
    organization_id     TEXT,
    image_cid           TEXT,
    image_ipfs_url      TEXT,
    image_gateway_url   TEXT,
    lat                 NUMERIC(9, 6),
    lon                 NUMERIC(9, 6),
    gps                 TEXT,
    notes               TEXT NOT NULL DEFAULT '',
    submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status              activity_status NOT NULL DEFAULT 'pending',
    review_note         TEXT NOT NULL DEFAULT '',
    reviewed_at         TIMESTAMPTZ,
    reward_id           TEXT,
    reward_tx_hash      TEXT,
    reward_amount       NUMERIC(18, 2),
    reward_token_type   TEXT,
    reward_minted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_activities_status ON activities (status);
CREATE INDEX IF NOT EXISTS idx_activities_submitted_at ON activities (submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_activities_contributor_id ON activities (contributor_id);
CREATE INDEX IF NOT EXISTS idx_activities_organization_id ON activities (organization_id);

CREATE TABLE IF NOT EXISTS activity_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id     TEXT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_events_activity_id ON activity_events (activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_created_at ON activity_events (created_at DESC);

COMMIT;

