-- Ocean Cleanup Backend
-- PostgreSQL schema for the current JSON-backed API

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'contributor', 'verifier');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
        CREATE TYPE activity_status AS ENUM ('pending', 'rejected', 'approved');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id              TEXT PRIMARY KEY,
    first_name      TEXT NOT NULL,
    last_name       TEXT NOT NULL,
    email           TEXT NOT NULL,
    username        TEXT NOT NULL,
    password_hash   TEXT NOT NULL,
    role            user_role NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    organization_id UUID REFERENCES organizations(org_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_username_unique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS activities (
    id                  TEXT PRIMARY KEY,
    category            TEXT NOT NULL,
    location            TEXT NOT NULL,
    quantity            NUMERIC(12, 2) NOT NULL CHECK (quantity >= 0),
    volunteers          INTEGER NOT NULL DEFAULT 0 CHECK (volunteers >= 0),
    evidence_hash       TEXT,
    contributor_id      TEXT,
    organization_id     TEXT,
    image_cid           TEXT,
    image_ipfs_url      TEXT,
    image_gateway_url   TEXT,
    lat                 NUMERIC(9, 6),
    lon                 NUMERIC(9, 6),
    gps                 TEXT,
    notes               TEXT NOT NULL DEFAULT '',
    submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status              activity_status NOT NULL DEFAULT 'pending',
    review_note         TEXT NOT NULL DEFAULT '',
    reviewed_at         TIMESTAMPTZ,
    reward_id           TEXT,
    reward_tx_hash      TEXT,
    reward_amount       NUMERIC(18, 2),
    reward_token_type   TEXT,
    reward_minted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_activities_status ON activities (status);
CREATE INDEX IF NOT EXISTS idx_activities_submitted_at ON activities (submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_activities_contributor_id ON activities (contributor_id);
CREATE INDEX IF NOT EXISTS idx_activities_organization_id ON activities (organization_id);

CREATE TABLE IF NOT EXISTS activity_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id     TEXT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    event_type      TEXT NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_events_activity_id ON activity_events (activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_created_at ON activity_events (created_at DESC);

CREATE TABLE IF NOT EXISTS notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role  user_role NOT NULL,
    recipient_id    TEXT,
    activity_id     TEXT REFERENCES activities(id) ON DELETE SET NULL,
    title           TEXT NOT NULL,
    message         TEXT NOT NULL,
    link            TEXT,
    payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_role ON notifications (recipient_role);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_id ON notifications (recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);

CREATE TABLE IF NOT EXISTS user_login (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    username        TEXT NOT NULL,
    role            user_role NOT NULL,
    ip_address      TEXT,
    socket_id       TEXT,
    user_agent      TEXT,
    login_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_login_user_id ON user_login (user_id);
CREATE INDEX IF NOT EXISTS idx_user_login_login_at ON user_login (login_at DESC);

CREATE TABLE IF NOT EXISTS organizations (
    org_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    region          TEXT,
    country         TEXT,
    parent_org_id   UUID REFERENCES organizations(org_id),
    contact_email   TEXT,
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active       BOOLEAN NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_organizations_is_active  ON organizations (is_active);
CREATE INDEX IF NOT EXISTS idx_organizations_parent_org ON organizations (parent_org_id);
CREATE INDEX IF NOT EXISTS idx_organizations_joined_at  ON organizations (joined_at DESC);

COMMIT;


